---
parser: babel-eslint
parserOptions:
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures:
    jsx: true
    impliedStrict: true
    experimentalObjectRestSpread: true
globals:
  Promise: true
env:
  browser: true
  jest: true
  node: true
  commonjs: true
extends:
  - eslint:recommended
  - plugin:react/recommended
rules:
  no-empty: warn
  no-console: off
  semi:
    - error
    - never
  react/jsx-sort-prop: true
